# Generated by Django 4.2.9 on 2024-01-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_registration_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='http://placehold.it/600x400', upload_to='media', verbose_name='Avatar'),
        ),
    ]
