# Generated by Django 4.2.9 on 2024-01-17 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(default='2020-10-10', verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=500, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
