# Generated by Django 4.2.9 on 2024-01-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcard',
            name='items',
        ),
        migrations.AddField(
            model_name='shopcard',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cards', to='shop.clothes', verbose_name='Items in ShopCard'),
        ),
    ]
