# Generated by Django 4.2.9 on 2024-01-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_shopcard_items_shopcard_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcard',
            name='items',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cards', to='shop.clothes', verbose_name='Items in ShopCard'),
        ),
    ]
