# Generated by Django 5.0 on 2024-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='shop.clothes', verbose_name='Items in Order'),
        ),
    ]
