# Generated by Django 5.0 on 2024-01-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_shopcard_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='shop.shopcard', verbose_name='Items in Order'),
        ),
        migrations.AlterField(
            model_name='shopcard',
            name='items',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cards', to='shop.clothes', verbose_name='Items in ShopCard'),
        ),
    ]
