# Generated by Django 5.0 on 2024-01-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_order_items_alter_shopcard_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='item_names',
            field=models.TextField(blank=True, verbose_name='Item Names'),
        ),
    ]
