# Generated by Django 5.0 on 2024-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_order_items_order_item_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='shop.shopcard', verbose_name='Items in Order'),
        ),
    ]
