# Generated by Django 5.0 on 2024-01-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
