# Generated by Django 5.0 on 2024-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_names',
            field=models.JSONField(blank=True, default=list, verbose_name='Item Names'),
        ),
    ]
