# Generated by Django 5.0 on 2024-01-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_order_item_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.clothes', verbose_name='Image URL'),
        ),
    ]
