# Generated by Django 5.0 on 2024-01-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_order_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image_url',
        ),
    ]
